boostorg/build

doc/src/reference.xml
Hey there,
I don't know if you accept that kind of PRs but I was reading the reference documentation and I spotted some typos so I decided to fix them. ;)
Lemme know if something is wrong!
=> Fix typos in reference documentation

src/engine/build.bat, src/engine/build.jam, src/tools/msvc.py
Path autodetection to VS works only if it installed to default path
=> Some fixes for VS2017

src/tools/quickbook.jam
I've just added strict mode to develop in the quickbook module.
=> Add a feature for using quickbook's strict mode

src/tools/lzma.jam
Just a quick hack to allow to implement LZMA
compressor and decompressor in iostreams (see also
trac ticket 7534).
Probably needs to be refined at some point by someone
who knows what they are doing, but it seems to work in principle.
=> Add lzma.jam file.

src/engine/fileunix.c
Sort file lists
to enable more reproducible builds
without patching individual build definitions like
https://github.com/boostorg/container/pull/50
note: when building on *NIX, it requires systems compliant to 4.3BSD, POSIX.1-2008
=> sort file lists

doc/src/tools.adoc, example/sass/importing.scss, example/sass/include/foobar.scss, example/sass/jamroot.jam, example/sass/singleton.sass, example/sass/singleton.scss, src/tools/sass.jam, src/tools/types/css.jam, src/tools/types/sass-type.jam
Adds sass tool that can be used to convert *.sass and *.scss files
into *.css files.
=> Support for SASS transpilers.

src/engine/config_toolset.bat
=> Workaround vsdevcmd_end.bat switching to %USERPROFILE%\Source

src/engine/debugger.c
error on fork had no output and did not end correctly
=> gcc compiler warnings identified unhandled error cases

src/tools/saxonhe.jam
Will be used in generation of Beast reference.
=> Add support for SaxonHE for xsl processing

src/engine/jam.c
* src/engine/jam.c
( main ): Read KEEP_GOING and PARALLELISM before calls to parse-file, so they are respected also here.
=> Read options before parse

src/tools/builtin.py, src/tools/features/instruction-set-feature.jam, src/tools/gcc.jam, src/tools/gcc.py
The z15 is the latest model of s390x
=> Add z15 to the s390x platform

src/tools/generators/archive-generator.jam, src/tools/generators/linking-generator.jam
This fixes the problem described in #493.
=> Fix errors when a source doesn't have a type; refs #493

src/tools/package.jam
=> make explicit only the targets created by the rule

src/tools/gcc.jam
We need to be able to add "D" option for deterministic builds.
=> Allow replacing ar flags

src/build/targets.jam
got an unknown-error instead of error-message without the import.
=> import errors.error in targets.resolve-reference.

.vscode/launch.json
=> Add missing arguments separator in launch.json [ci skip]

.gitignore
Since the project includes some support for VSCode...
=> Ignore VSCode workspace file [ci skip]

src/engine/execvms.cpp, src/engine/function.cpp, src/engine/hcache.cpp, src/engine/hdrmacro.cpp, src/engine/headers.cpp, src/engine/jam.cpp
=> Print fopen fail reason

src/tools/clang.jam, src/tools/cray.jam, src/tools/embarcadero.jam, src/tools/features/cxxstd-feature.jam, src/tools/gcc.jam, src/tools/pgi.jam, src/tools/xlcpp.jam
The -std=c++20 is supported by clang 10.
=> Add cxxstd value 20 for C++20

src/tools/msvc.jam
This also removes ambiguous implicit address-model ARM/ARM64 values.
Closes #128
Closes #277
=> Default MSVC to a native platform
